# Домашнее задание №1: Классификация. 
# Логистическая регрессия и kNN.

*While the machines are being fixed.*

Формат сдачи будет объявлен позднее. Либо это будет проверяющая система, либо telegram-бот. 

<span style="color: red; font-size: 14pt">Дедлайн: 3 марта 23:59</span>

### Часть 1. Небольшой numpy-разогрев. (10%)

In [1]:
import numpy as np
import pandas as pd

In [12]:
# Создайте случайную матрицу A размерами 10 на 10 из целых чисел от 0 до 100
# hint: np.random.randint

# Ваш код здесь
A = np.random.randint(0, 100, (10,10))
print(A)

[[84 85 83 38 12 78  3 40 10 29]
 [71 30 26 24 96 40 71 75 64 16]
 [51 10  8 53 24 50 42 11 46 57]
 [42 71 72  9 61 13 70 71 91 38]
 [67 13 75 35 65 97 56 42  1 35]
 [68 82 25 20 26 75 44 36 37 92]
 [15 38 93 67 46  3  0 46 79 77]
 [57 74 76  9  5 68 24 84 67  5]
 [38 40 65 22 21 24 17 20 53 18]
 [49 62 40 14 82 83 86 41 95 63]]


In [15]:
# Посчитайте средние значения в матрице по столбцам

# Ваш код здесь
np.average(A, axis=0)

array([54.2, 50.5, 56.3, 29.1, 43.8, 53.1, 41.3, 46.6, 54.3, 43. ])

In [17]:
# Транспонируйте матрицу A

# Ваш код здесь
A.T

array([[84, 71, 51, 42, 67, 68, 15, 57, 38, 49],
       [85, 30, 10, 71, 13, 82, 38, 74, 40, 62],
       [83, 26,  8, 72, 75, 25, 93, 76, 65, 40],
       [38, 24, 53,  9, 35, 20, 67,  9, 22, 14],
       [12, 96, 24, 61, 65, 26, 46,  5, 21, 82],
       [78, 40, 50, 13, 97, 75,  3, 68, 24, 83],
       [ 3, 71, 42, 70, 56, 44,  0, 24, 17, 86],
       [40, 75, 11, 71, 42, 36, 46, 84, 20, 41],
       [10, 64, 46, 91,  1, 37, 79, 67, 53, 95],
       [29, 16, 57, 38, 35, 92, 77,  5, 18, 63]])

In [18]:
# Перемножьте поэлементно матрицу A и транспонированную матрицу A 

# Ваш код здесь
A * A.T

array([[7056, 6035, 4233, 1596,  804, 5304,   45, 2280,  380, 1421],
       [6035,  900,  260, 1704, 1248, 3280, 2698, 5550, 2560,  992],
       [4233,  260,   64, 3816, 1800, 1250, 3906,  836, 2990, 2280],
       [1596, 1704, 3816,   81, 2135,  260, 4690,  639, 2002,  532],
       [ 804, 1248, 1800, 2135, 4225, 2522, 2576,  210,   21, 2870],
       [5304, 3280, 1250,  260, 2522, 5625,  132, 2448,  888, 7636],
       [  45, 2698, 3906, 4690, 2576,  132,    0, 1104, 1343, 6622],
       [2280, 5550,  836,  639,  210, 2448, 1104, 7056, 1340,  205],
       [ 380, 2560, 2990, 2002,   21,  888, 1343, 1340, 2809, 1710],
       [1421,  992, 2280,  532, 2870, 7636, 6622,  205, 1710, 3969]])

In [21]:
# Посчитайте dot product (результат матричного умножения) матрицы A на саму себя и запишите в матрицу B
# https://en.wikipedia.org/wiki/Dot_product

# Ваш код здесь
B = A@A
print(B)

[[29154 25042 20561 13140 19212 26986 20161 21545 22656 20005]
 [28136 25227 33912 16236 19397 28839 16515 24054 23132 19975]
 [18434 20674 21435  9642 15484 18254 14401 15562 20123 17257]
 [28007 22828 30797 17455 22502 27101 19328 24028 28357 19908]
 [27784 25565 26184 16005 18411 29484 18667 20746 22407 25700]
 [29117 27918 26154 13841 24673 29345 22637 23917 28288 23309]
 [24198 20284 23037 11914 21418 24313 23116 19871 27698 17279]
 [27194 24223 23157 13494 15595 24715 16104 21668 23692 17731]
 [17601 14245 15739  9999 12658 16114 12385 12803 16043 12723]
 [32608 29299 35041 19229 27164 33218 23470 26359 31286 28237]]


### Часть 2. Логистическая регрессия и kNN.

Будем работать с подвыборкой из [данных о типе лесного покрытия из репозитория UCI](http://archive.ics.uci.edu/ml/datasets/Covertype). Доступно 7 различных классов. Каждый объект описывается 54 признаками, 40 из которых являются бинарными. Описание данных доступно по ссылке, а так же в файле `covtype.info.txt`.

In [25]:
all_data = pd.read_csv('/home/jeny/ml_mipt_2019/ml-mipt/Homeworks/HW_1_Linclass_kNN/forest_dataset.csv')
all_data.shape

(10000, 55)

Выделите 20% данных в `delayed_data` в качестве выборки, на которой будет производиться финальное сравнение моделей, в `all_data` поместите оставшиеся 80%.

In [26]:
# Ваш код здесь


Выделим значения метки класса в переменную `labels`, признаковые описания в переменную `feature_matrix`. Так как данные числовые и не имеют пропусков, переведем их в `numpy`-формат с помощью метода `.values`.

In [0]:
labels = all_data[all_data.columns[-1]].values
feature_matrix = all_data[all_data.columns[:-1]].values

#### 2.1 Двуклассовая классификация (10%)

Для начала будем работать только с двумя типами лесного покрытия. Обучите линейный классификатор для разделения двух классов. Данные разделите на train и test с помощью `train_test_split`.

In [0]:
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, accuracy_score

In [0]:
two_class_labels_indices = (labels == 1) + (labels == 2)

two_class_feature_matrix = feature_matrix[two_class_labels_indices]
two_class_labels = labels[two_class_labels_indices]

In [0]:
train_feature_matrix, test_feature_matrix, train_labels, test_labels = <your_code_here>

Обучите логистическую регрессию. Оцените качество классификации на отложенной выборке с помощью `accuracy` и `f1_score` ([Wikipedia](https://en.wikipedia.org/wiki/F1_score)).

In [0]:
lr_clf = LogisticRegression()

In [0]:
# Ваш код здесь

#### 2.2 Многоклассовая классификация: логистическая регрессия (40%)

**Комментарий:**

*Логистическая регрессия позволяет решать и задачу многоклассовой классификации. Класс ``LogisticRegression`` позвляет это делать двумя способами:* 
- *1. Стандартный One vs Rest (т.е. каждый класс отделяется от всех других). Параметр `multi_class='ovr'`.*
- *2. Используюя кросс-энтропию (оценивается сразу вектор вероятностей принадлежности классам). Параметр `multi_class='multinomial'`.*

*По умолчанию будем использовать второй способ.*


Теперь будем работать со всеми 7 типами покрытия (данные уже находятся в переменных `feature_matrix` и `labels`, если Вы их не переопределили). Разделите выборку на обучающую и тестовую с помощью метода `train_test_split`, используйте значения параметров `test_size=0.2`, `random_state=42`. Обучите логистическую регрессию  на данном датасете.

In [0]:
lr_clf = LogisticRegression()

# Ваш код здесь

С помощью 5-кратной кросс-валидации (`GridSearchCV`) подберите оптимальное значение параметров `С` и `penalty`. Для параметра `C` используйте набор значений `np.linspace(0.01, 1, 10)`, а для `penalty` - `['l1', 'l2']`. Критерий качества `scoring = 'accuracy'`.

In [0]:
# Ваш код здесь

Постройте графики средних значений критерия качества `accuracy` для типов регуляризации `l1` и `l2` в зависимости от коэффициента регуляризации `C`.

In [0]:
# Ваш код здесь

Проанализируйте полученные графики. Чему равны найденные оптимальные значения параметров `C` и `penalty`?

In [0]:
# Ваш код здесь

Используя найденные оптимальные значения `C` и `penalty`, обучите логистическую регрессию на обучающей выборке (train) и вычислите вероятности принадлежности к классам для тестовой (test)  выборки (`best_lr_clf.predict_proba`).

In [0]:
best_lr_clf = LogisticRegression(<your_best_params_here>)

# Ваш код здесь

Для полученной матрицы вычислите усредненные по всем объектам из тестовой выборки значения вероятностей принадлежности к классам. Сравните ее оценкой вероятности принадлежности к классу на основе частот меток классов в обучающей выборке.

In [0]:
# Ваш код здесь

#### 2.3 Многоклассовая классификация: kNN (30%).

Вспомним первое занятие. Обучите на том же датасете `KNeighborsClassifier` из `sklearn`.

In [0]:
from sklearn.neighbors import KNeighborsClassifier

# Ваш код здесь

Попробуйте использовать различные стратегии вычисления весов: `[‘uniform’, ‘distance’]`. Выберите одно из них самостоятельно. Чем обоснован Ваш выбор?

Переберите по сетке от `1` до `10` параметр числа соседей. Покажите на графике, как менялись значения критерия качества `accuracy` при изменении числа соседей.

In [0]:
# Ваш код здесь

Используя найденное оптимальное число соседей, вычислите вероятности принадлежности к классам для тестовой выборки (`.predict_proba`).

In [0]:
# Ваш код здесь

#### 2.4 Сравнение результатов логистической регрессии и kNN (10%).

В реальной жизни новые данные становятся доступны с течением времени. Сравните качество Вашей лучшей модели логистической регресии и лучшего kNN  на отложенной выборке `delayed_data`. Какая из моделей показала лучший результат?

In [0]:
# Ваш код здесь